apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    metadata:
      labels:
        workload-tier: workload
        role: workload
    spec:
      # Reference to EC2NodeClass
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      # Node requirements
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]  # Start with on-demand, can add spot later
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - t3.small
            - t3.medium
            - t3.large
            - t3.xlarge
  # Limits
  limits:
    cpu: 1000  # Max 1000 CPU cores
    memory: 1000Gi  # Max 1000 GiB memory
  # Disruption (consolidation)
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s

---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  # AMI selector (required) - matches EKS optimized AL2 AMIs for Kubernetes 1.29
  # Use owner and name pattern to match only AL2 AMIs (not AL2023)
  amiSelectorTerms:
    - owner: "amazon"
      name: "amazon-eks-node-1.29-*"
  
  # AMI family (use EKS optimized AL2)
  amiFamily: AL2
  
  # Subnet selector (uses tags we set)
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-platform
  
  # Security group selector
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/eks-platform: owned
  
  # Instance profile for nodes
  instanceProfile: KarpenterNodeInstanceProfile-eks-platform
  
  # User data (bootstrap script for EKS)
  userData: |
    #!/bin/bash
    /etc/eks/bootstrap.sh eks-platform
  
  # Block device mappings
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        deleteOnTermination: true
        encrypted: true

