apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/RitzLearnsK8s/data-platform-infra.git
    targetRevision: main
    path: clusters/eks-platform/apps/guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: team-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # team-a namespace already exists
      - PruneLast=true
  revisionHistoryLimit: 3


